### ISSUE TITLE
Écrire des tests pour les formules

### ISSUE THREAD

**Issue by arnaud-m** [arnaud-m/XLUniv#2]
Écrire des tests pour les formules (statistiques et notation).
Les fonctions doivent vérifier la chaîne de caractère contenant la formule excel. 
Inspirez-vous des exemples de la documentation.
Vous travaillerez sur une branche `test`.

**Comment by arnaud-m** [comment]
Fonctions `GetGradeFormula` et `GetStatFormula`
Vous devez écrire des tests du style en faisant varier les paramètres des fonctions.
```
expect_equal( "LA BONNE RÉPONSE", GetStatFormula(n = 5, m = 10))
```

**Comment by ThomasDissaux** [comment]
doit-on aussi vérifier que les formules "COUNTA", "AVERAGE", "STDEV", "COUNTIF", "COUNTIF", "COUNTIF" fonctionnent avec excel?
