### ISSUE TITLE
Tester le classeur 'Sésame'

### ISSUE THREAD

**Issue by arnaud-m** [arnaud-m/XLUniv#3]
Écrire une fonction de test écrivant une liste d'étudiants et de notes dans un classeur.
Puis, lire le classeur et vérifier les valeurs attendues pour les notes et statistiques.

**Comment by ThomasDissaux** [comment]
bonjours, en vérifiant la fonction CreateSesameWorkbook, je me suis rendu compte que vous corrigez l'erreur signalé hier grâce à : GetGradeFormula(k, m1, coefs, max, round)   où m1 est la dernière colonne de df.

Voulez vous laisser les fonction comme elles étaient ou corriger GetGradeFormula puis écrire:
GetGradeFormula(k, m1+1, coefs, max, round) dans CreateSesameWorkbook?

**Comment by arnaud-m** [comment]
Non, je pense que ta spécification est plus cohérente. 
Essaie de finir la tâche précédente (en mettant à jour la fonction CreateSesameWorkbook) avant de passer à celle-ci.
